version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "55432:5432"
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
